# This is a basic generic Makefile.
#
# To use:
#	make name_of_c_file_but_without_suffix
#
# For example:
#	make test_1
#
#	I use gcc as my compiler, and I set all the warnings, as well as debug information (for pedagogical reasons).

CC = gcc
CFLAGS = -Wall -Wextra -g
